### ISSUE TITLE
Improve response messaging

### ISSUE THREAD

**Issue by janmichek** [aeternity/smart-contract-verifier#39]
There is a different form of error response from the `/contracts` endpoint

![image](https://github.com/aeternity/smart-contract-verifier/assets/15363559/e1afbe6a-ab2a-44f9-b0c8-a81ff6107705)

![image](https://github.com/aeternity/smart-contract-verifier/assets/15363559/f0c6e73d-3561-4644-a815-3ff6c7b4b561)

status vs statusCode
error vs message

Could you align this to the same key naming? That would make things much easier on frontend so I don't have to adapt the error response with additional logic.

Another discrepancy is between the `/contracts` and `/check` endpoints.
From the check endpoint, I am getting human-readable responses `fail` or `success`
From the contracts endpoint, I am getting error codes like `409` or `422`.

This would also be nice to align. I prefer to use the human-readable format on FE. I think you can still attach both statusCode and status.

**Comment by lukeromanowicz** [comment]
@janmichek I unified all errors to contain `statusCode: number` and `message: string | string[]`

That means I also had to change the /check endpoint so that in scenario of failed verification the response is also 200, and you can read the result of the verification from 'status' property which has one of the following values:

```
export enum VerificationStatus {
  NEW = 'new', // just added to the database 
  PENDING = 'pending', // pushed to the verification queue
  PROCESSING = 'processing', // undergoing verification
  SUCCESS = 'success', // success
  FAIL_RETRY = 'fail_retry', // internal error, we will retry after some time
  FAIL = 'fail', // verification unsuccessful
}
```

**Comment by janmichek** [comment]
Thanks for the unification.
The rest of my request I imagined differently.

> This would also be nice to align. I prefer to use the human-readable format on FE. I think you can still attach both statusCode and status.

The status code is not a very interesting piece of information for me. I can get it from headers.
As stated before I prefer to operate with human-readible response. For example responses `status: fail` or `status: success`...
You can keep the `statusCode ` but I don't plan to use it. For my implementation is too low-level
I wanted to ask you to translate codes to statuses on the server side, so I don't need to translate it on FE.

**Comment by lukeromanowicz** [comment]
@janmichek StatusCode part is generated automatically by Nest and the integrated plugins. Considering that a lot of errors are auto-handled, I would prefer to avoid changing this since it would require writing a lot of manual handlers. Isn't the most important place where a human-readable status code as text is present - i.e. contract verification status check endpoint? Everywhere else you get either 200 - it went good, 404 - it wasn't found, or other error with the exact human-readable message of what went wrong

**Comment by janmichek** [comment]
> @janmichek statusCode part is generated automatically by Nest and the integrated plugins. Considering that a lot of errors are auto-handled, I would prefer to avoid changing this since it would require writing a lot of manual handlers. Isn't the most important place where a human-readable status code as text already there - i.e. contract verification status check endpoint? Everywhere else you get either 200 - it went good, 404 - it wasn't found, or other error with the exact human-readable message of what went wrong

Ok, so could you provide me the map of statusCodes translated to status 'words'? The API documentation is not complete yet, right? so can you provide me here in the comment and I will translate it on FE.

**Comment by lukeromanowicz** [comment]
@janmichek which endpoints do you have specifically in mind?

**Comment by janmichek** [comment]
POST /contracts/{contractId}
GET /contracts/{contractId}
GET /contracts/{id}/check/{submissionId}

**Comment by janmichek** [comment]
I think I made it run

```
    if (code === 400 || code === 422) {
      return 'fail'
    }
    if (code === 409) {
      return 'conflict'
    }
```
example for POST /contracts/{contractId} 

Is there something else?

**Comment by lukeromanowicz** [comment]
@janmichek I'll deep dive into the code later today to make sure I'll provide you all cases

**Comment by lukeromanowicz** [comment]
@janmichek 
POST /contracts/{contractId} can generate:
HTTP 400 + message | messages[] if the input data validation failed or recaptcha is enabled and its verification failed
HTTP 409 + message | messages[] if the contract is already verified
HTTP 422 + message | messages[] if the connection to remote Node API is down or (more likely) the contract hash is correct but it was not deployed in this network (e.g. testnet instead of mainnet)

Otherwise HTTP 200 + submissionId

---

GET /contracts/{contractId}
404 if the contract was not verified (it can as well not exist in given network, since it's not calling Node API to check it)
or
HTTP 200 + verified contract details

---

GET /contracts/{id}/check/{submissionId}
returns 404 if either sumissionId is wrong or the corresponding contractId is wrong
or
HTTP 200 + submission status

---

Apart from that, all of the endpoints may return:
HTTP 500 + message | messages[] if there was unexpected backend error

**Comment by janmichek** [comment]
Cool, thanks for the translation
